# Generated by Django 3.2.6 on 2021-08-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20210831_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='readtext',
            field=models.TextField(blank=True, null=True),
        ),
    ]
