# Generated by Django 3.2.6 on 2021-08-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_readtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='readtext',
            field=models.TextField(blank=True, default='a', null=True),
        ),
    ]
